sudo: false

language:
    - php
    - node_js

php:
    - 5.5

node_js:
    - stable

env:
    global:
        - PANTHEON_UUID='123e4567-e89b-12d3-a456-426655440000'
        - PANTHEON_SITE='example'
        - WP_VERSION=latest
        - WP_MULTISITE=0

branches:
    only:
        - master

install:
    # Gathering tips from: https://gist.github.com/iamEAP/8855842
    # Dynamic hosts through Pantheon mean constantly checking interactively
    # that we mean to connect to an unknown host. We ignore those here.
    - ssh-keyscan -p 2222 codeserver.dev.$PANTHEON_UUID.drush.in >> ~/.ssh/known_hosts
    - git config --global user.name "Travis CI"
    - git config --global user.email "travis-ci@xwp.co"

    # Install Terminus
    #- mkdir -p $HOME/pantheon-cli
    #- curl -L https://github.com/pantheon-systems/cli/archive/master.tar.gz | tar xvz --strip-components=1 -C $HOME/pantheon-cli
    #- ( cd $HOME/pantheon-cli && composer install )
    #- export PATH="$HOME/pantheon-cli/bin:$PATH"

before_script:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - source $DEV_LIB_PATH/travis.before_script.sh
    - export LIMIT_TRAVIS_PR_CHECK_SCOPE=patches
    - git remote add pantheon ssh://codeserver.dev.$PANTHEON_UUID@codeserver.dev.$PANTHEON_UUID.drush.in:2222/~/repository.git

script:
    - $DEV_LIB_PATH/travis.script.sh

after_script:
    - $DEV_LIB_PATH/travis.after_script.sh

after_success:
    - if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then git fetch pantheon && git merge -m "Merge changes from pantheon into github" pantheon/master && git push origin HEAD:master && git push pantheon HEAD:master; fi
    # @todo If not master, we can push to a feature branch on Pantheon and create a multidev environment if it doesn't already exist.
    # if [ $TRAVIS_BRANCH != 'master' ]; then if ! terminus site --site=$PANTHEON_SITE env-exists --env=$TRAVIS_BRANCH; then terminus site --site=$PANTHEON_SITE create-env --env=$TRAVIS_BRANCH; fi; git push pantheon; fi
